defaults:
  - _self_
  - model: small
  - override hydra/launcher: submitit_slurm

experiment: default

ngpus: 8
tokens: 50257

training:
  batch_size: 512
  accum: 1
  n_iters: 1300001
  snapshot_freq: 50000
  log_freq: 50
  eval_freq: 100
  snapshot_freq_for_preemption: 10000
  weight: standard
  snapshot_sampling: True
  ema: 0.9999

data:
  train: openwebtext
  valid: wikitext103
  cache_dir: /checkpoint/storygen/zqq/data/openwebtext

graph:
  type: uniform
  file: data
  report_all: False

noise:
  type: geometric
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 128
  noise_removal: True

eval:
  batch_size: 512
  perplexity: True
  perplexity_batch_size: 32

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  warmup: 2500
  grad_clip: 1.


hydra:
  run:
    dir: /checkpoint/storygen/zqq/sedd/exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: /checkpoint/storygen/zqq/sedd/exp/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    timeout_min: 10079
    account: storygen
    qos: storygen_high
    cpus_per_task: 50
    gpus_per_node: 8
    nodes: 1
    constraint: null
    submitit_folder: /checkpoint/storygen/zqq/sedd/exp/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/slurm
  job:
    name: ${experiment}
